name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-format:
    name: Test format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
          cache: false

      - name: Setup node/yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install packages
        run: yarn

      - name: Check Contracts Format
        run: yarn format --check

      - name: Make sure contracts can be built
        run: yarn build
